apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/mintmaker/config/default?ref=062080578747badc43ab7b74db501f9e429901f8
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=062080578747badc43ab7b74db501f9e429901f8

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/redhat-user-workloads/konflux-mintmaker-tenant/mintmaker-refactoring-pipelinerun
  newTag: 097f4999463b97a86c48bc67e938f1f87f8eb695
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: 289fc1f3a79aaf172bff9def716e2f864a7f25c4

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - path: manager_patch.yaml

configurations:
- kustomizeconfig.yaml
